// Euler_029_CPP.cpp : This file contains the 'main' function. Program execution begins and ends there.
// Distinct Powers
// How many distinct terms are in the sequence generated by ab for 2 <= a <= 100 and 2 <= b <= 100?

#include <iostream>
#include <vector>
#include <algorithm>
#include <math.h>

using namespace std;

int main()
{
    vector<double> vect;
    for (int a = 2; a < 101; a++)
        for (int b = 2; b < 101; b++)          
            vect.push_back(1.0*(log(pow(b, a))));
       
    cout << "The original size is: " << vect.size() << endl;
    sort(vect.begin(), vect.end());
    vect.erase(unique(vect.begin(), vect.end()), vect.end());     
    cout << "The final size is: " << vect.size() << endl;
}
